### ISSUE TITLE
Syntax

### ISSUE THREAD

**Issue by karimzmi** [flipkart-incubator/zjsonpatch#1]
Would it be possible to follow the syntax referenced in the RFC such as op for operation (instead of o) and value (instead of v) etc? Thanks.

**Comment by vishwakarma** [comment]
Sure, i ll make this change.

**Comment by vishwakarma** [comment]
HI
The is fixed. Please use latest version 0.1.10.
Since in 0.1.10 , i have replaced o with op, v with value etc, hence this version wont be compatible with diffs generated by older version. Please take-care before using this latest version.

**Comment by Bubai14** [comment]
I am using zjsonpatch for generating the difference between the two jsons. It gives me the modified value, but how to get the old value from this library?

**Comment by holograph** [comment]
If by "original value" you mean the "value before a REPLACE op", you can
pass a flag set that excludes OMIT_VALUE_ON_REPLACE (IIRC) to
JsonDiff.asJson.

**Comment by Bubai14** [comment]
Thanks for response @holograph . But in the version 0.33 I am only able to find OMIT_VALUE_ON_REMOVE option in the DiffFlags enum. Can you please clarify in detail?

**Comment by holograph** [comment]
My bad, the library never output the original value on REPLACE, only on REMOVE. See example below. In other news, I just realized we're continuing on an old (and irrelevant) issue, feel free to open a new issue for any questions/bug reports/feature requests...

```java
        ObjectMapper mapper = new ObjectMapper();

        ObjectNode original = mapper.createObjectNode();
        ObjectNode empty = mapper.createObjectNode();
        original.put("value", 1);

        JsonNode defaultDiff = JsonDiff.asJson(original, empty);
        System.out.println("Default flags:\n" + mapper.writeValueAsString(defaultDiff));

        EnumSet<DiffFlags> flags = DiffFlags.defaults();
        flags.remove(DiffFlags.OMIT_VALUE_ON_REMOVE);
        JsonNode customDiff = JsonDiff.asJson(original, empty, flags);
        System.out.println("Without OMIT_VALUE_ON_REMOVE:\n" + 
        mapper.writeValueAsString(customDiff));

/*
  -- Output --
  Default flags:
  [{"op":"remove","path":"/value"}]
  Without OMIT_VALUE_ON_REMOVE:
  [{"op":"remove","path":"/value","value":1}]
*/
```
