### ISSUE TITLE
Taking too much

### ISSUE THREAD

**Issue by NidhiPaleja** [flipkart-incubator/zjsonpatch#10]
Hi,
I am using jsonpatch in my application to compare the json files and thereby generate comparison report of the same.
In the jsonpatch there one code present to create the matrix in lenth() method in com.topologi.diffx.algorithm.DiffXFitopsy.java.
It has nested for loop because of which my application is taking very long time and sometimes gets stuck badly.
Can you plz help me out I am badly stuck and need to resolve this issue ASAP

**Comment by vishwakarma** [comment]
Hi Nidhi
This project doesn't have DiffXFitopsy.java, Can you please check over it.
Further can you please check the size of your input json over which you are computing diff ?

**Comment by vishwakarma** [comment]
Hey , Did you look into your project, for DiffXFitopsy.java ?
