### ISSUE TITLE
Diff two json with list node, same values and different orders

### ISSUE THREAD

**Issue by yuanmei-norra** [flipkart-incubator/zjsonpatch#101]
## Expected Behavior
shouldn't have patch, I think the JsonDiff should be more intelligent.

## Actual Behavior
have patch value
[{"op":"add","path":"/ids/0","value":103},{"op":"add","path":"/ids/1","value":102},{"op":"remove","path":"/ids/3","value":102},{"op":"remove","path":"/ids/3","value":103},{"op":"add","path":"/mails/0","value":"aaa@abc.net"},{"op":"remove","path":"/mails/2","value":"aaa@abc.net"}]

## Steps to Reproduce the Problem
json 1: 
{
  "ids": [
    101,
    102,
    103
  ],
  "mails": [
    "bbb@abc.com",
    "aaa@abc.net"
  ]
}
json 2:
{
  "ids": [
    103,
    102,
    101
  ],
  "mails": [
    "aaa@abc.net",
    "bbb@abc.com"
  ]
}
## Specifications
EnumSet<DiffFlags> flags = DiffFlags.dontNormalizeOpIntoMoveAndCopy().clone();
ArrayNode patch = (ArrayNode) JsonDiff.asJson(jsonNode1, jsonNode2, flags);

Library Version:  
Language Java 1.8

**Comment by holograph** [comment]
I'm not sure what you're getting at here - order matters for JSON documents, and these two documents are clearly not identical. Am I missing something?

**Comment by LouizFC** [comment]
I concur with @holograph 

Attribute ordering (by attribute, I mean key value pairs) is irrelevant ,aside from some use cases, and of course, the stetic appeal. But the [JSON Patch Specification says at section 4.6](https://tools.ietf.org/html/rfc6902#section-4.6) that arrays are considered equal if they have the same elements in the same order.

**Comment by yuanmei-norra** [comment]
I got your point.  Because I have two entity, and convert to json, then do json diff. But the order maybe different for some arrays(although have same values), so I cannot do json diff directly. I need to sort them first.
