### ISSUE TITLE
Add possibility to treat arrays as values when computing json diff

### ISSUE THREAD

**Issue by karolovbrat** [flipkart-incubator/zjsonpatch#11]
I was wondering whether you would be willing to accept an extension to the library which could treat the json arrays as values when producing the diff?

This would mean adding the possibility to report the change:
`{"array":["A","B","C"]} -> {"array":["C","A","B"]}` 
as
`[{"op":"replace", "path":"/array", "value":["C","A","B"]}]`

The idea is to have the possibility to know that an array has changed without knowing every little change.

**Comment by vishwakarma** [comment]
1. This would deviate from the specification mentioned in RFC 6902.
2. But i would be happy to accept this change as a new API in this library.
