### ISSUE TITLE
zjsonpatch no longer compatible with Java 6

### ISSUE THREAD

**Issue by dandoug** [flipkart-incubator/zjsonpatch#110]
## Expected Behavior
Expect to run programs with JDK 6

## Actual Behavior
Get
 
```
java.lang.UnsupportedClassVersionError: org/apache/commons/io/IOUtils : Unsupported major.minor version 51.0
```

## Steps to Reproduce the Problem
Run any simple test program with JDK 6

## Specifications

Library Version:  0.4.5
Language (e.g. Java 1.8, Scala, etc):

The problem is that zjsonpatch 0.4.5 introduced a dependency on on
```
       <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-collections4</artifactId>
            <version>4.2</version>
        </dependency>
```
which was build with Java 7

```
file IOUtils.class
IOUtils.class: compiled Java class data, version 51.0 (Java 1.7)
```

Since Java 6 is so old, suggest that simplest thing to do is just claim that zjsonpatch works for Java 7+

**Comment by vishwakarma** [comment]
Sure, Thank you
