### ISSUE TITLE
How to ignore certain elements and child element order

### ISSUE THREAD

**Issue by tutufool** [flipkart-incubator/zjsonpatch#118]
Someone recommend this library for my question:

https://stackoverflow.com/questions/62277192/how-to-compare-2-json-by-ignoring-some-attributes-and-child-element-orders

I'm wondering whether it's doable with zjsonpatch, and if yes, any document or code sample I can follow?

**Comment by holograph** [comment]
Ignoring an element can conceivably be a fairly easy feature to implement, but I'm not sure this makes sense in the scope of diffing/patching. What you're looking for involves considerable business logic and schema reasoning, neither of which makes sense to me in the context of JSON Patch (or JSON in general).

That being said, there's nothing stopping you from doing it anyway -- there's always the possibility I'm wrong :-)

**Comment by tutufool** [comment]
Ignoring element should be easy since I can do  raw data --- > Patch --- > filtered Patch with your lib.
I'm just wondering whether I can ignore the order of child, i.e: treat it as set rather than list.

**Comment by holograph** [comment]
JSON doesn't have the concept of sets, and child/array index order really matters (and is therefore baked into the JSON Patch RFC). Consequently the library has no built-in support for that, and in my opinion it would be inappropriate for a library purporting to be RFC-compliant; maybe @vishwakarma has different ideas though...

**Comment by tutufool** [comment]
Never mind, I find something that may work for my case:
https://github.com/lukas-krecan/JsonUnit#options


Anyway, thanks a lot!
