### ISSUE TITLE
Feature Request: How much deep a json should compare.

### ISSUE THREAD

**Issue by atul-chainthat** [flipkart-incubator/zjsonpatch#119]
Please Note: I am not aware if this functionality is already there in this library, but found this functionality in some of the javascript libraries.

Example 1:

original json:-
`{ 
    "employee":
    {
        "id": "1212",
        "fullName":"John Miles",
        "age": 34,
        "contact":
        {
            "email": "john@xyz.com",
            "phone": "9999999999",
            "address": { 
                 "country": "UK", 
                 "city": "London" 
            }
        }
    }
}`

modified json:-
`{ 
    "employee":
    {
        "id": "1212",
        "fullName":"John Miles",
        "age": 34,
        "contact":
        {
            "email": "john@xyz.com",
            "phone": "9999999999",
            "address": { 
                 "country": "UK", 
                 "city": "Manchester" 
            }
        }
    }
}`

Expecting a functionality on how much deeper json will compare
as we have made change in the city inside address inside contact.

(1) - JsonDiff.asJson(json1, json2, 1);   // Track changes within 1  level deep.
output should indicates that there is a change in `contact` and return the whole contact not just the new city value.
 

(2) - JsonDiff.asJson(json1, json2, 2);   // Track changes within 2  level deep.
output should indicates that there is a change in `address` and return the whole address not just the new city value.

**Comment by vishwakarma** [comment]
@atul-chainthat , Currently this functionality is not present in this library.
The whole idea of this library to minimise the the diff size thats why this feature is not present at this moment.
You may read about what all is supported here - https://tools.ietf.org/html/rfc6902 as this library is an implementation of this RPC.

Further, can you please provide a use-case where this feature would be useful ?

**Comment by vishwakarma** [comment]
No further response from the OP, closing the ticket
