### ISSUE TITLE
Link in title is a dead link.

### ISSUE THREAD

**Issue by quarterpastsix** [flipkart-incubator/zjsonpatch#137]
## Expected Behavior
link works

## Actual Behavior
link dont works

## Steps to Reproduce the Problem
click on link
http://tools.ietf.org/html/rfc6902 This is an implementation of ->RFC 6902 JSON Patch<- written in Java.

## Specifications
yes

Library Version:  
Language (e.g. Java 1.8, Scala, etc):

**Comment by holograph** [comment]
Strangely enough the behavior depends on your user agent; with Chrome it actually redirects to https://datatracker.ietf.org/doc/html/rfc6902. Either way, the documentation should be updated to reflect that

**Comment by vishwakarma** [comment]
Updated the dead links.
Thanks @quarterpastsix for pointing out.
