### ISSUE TITLE
Source files are without license headers

### ISSUE THREAD

**Issue by puntogil** [flipkart-incubator/zjsonpatch#24]
Hi
All java source files are without license headers.
Please, confirm the licensing of code and/or content/s, and add license headers.

https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

Thanks in advance
Regards

**Comment by vkovalchuk** [comment]
Excusez-moi mon amis Puntoqil, did you look at https://github.com/flipkart-incubator/zjsonpatch/blob/master/LICENSE? Do you need some coffee?

**Comment by puntogil** [comment]
Please, see https://www.apache.org/legal/src-headers.html "WHAT FILES IN AN APACHE RELEASE DO NOT REQUIRE A LICENSE HEADER?"

**Comment by puntogil** [comment]
Despite that it is licensed under a very permissive license, it is still licensed, and that needs to be made clear. This is necessary for this reason:
Not licensed code, read code not licensed under a certain license or missing any license information has to be assumed to be not licensed. Which means that it defaults to "all rights reserved" which pretty much means "don't touch, and sometimes better don't look at it". Adding the license header to the source makes this absolutely clear without any question.

Adding the license information does remove any ambiguity and clearly indicates your intentions.

**Comment by holograph** [comment]
I have no argument, just that IMO this is definitely a "pull request if you care enough" kind of situation...

**Comment by vishwakarma** [comment]
Thanks @puntogil  for PR for same.
