### ISSUE TITLE
Print diff on Console

### ISSUE THREAD

**Issue by Jainpriyal** [flipkart-incubator/zjsonpatch#37]
Is there a way I can print the diff of two jsonFiles on console instead of just printing the patch.
I am looking for something similar to the output generated by http://www.jsondiff.com/

Does this library has this feature? Is there a way I can use this library to print changes in console.

**Comment by vishwakarma** [comment]
Hi @Jainpriyal 
Currently this library doesn't provides diff as of http://www.jsondiff.com/, rather it provides diff patches. If you have 2 JSONFiles, then you may linux tools to get diffs Or alternatively you may use https://github.com/andreyvit/json-diff.
Thanks

**Comment by Jainpriyal** [comment]
Thanks for your response. But I am looking for the java library that I can use in my package and not command line tool. Please let me know if you know any. 

Thanks
Priyal
