### ISSUE TITLE
Value in remove operation

### ISSUE THREAD

**Issue by mlajtos** [flipkart-incubator/zjsonpatch#38]
Hello :)

Is there any reason why remove operation contains value field? E.g.
```javascript
{"op":"remove","path":"/age","value": "123"}
```
According to the [RFC](https://tools.ietf.org/html/rfc6902#section-4.2), the value should not be there.

**Comment by vishwakarma** [comment]
:)
The value field had been added by me to validate the key/value being removed in one my project, but later i solved that using versioning of whole target json document.
Please feel free to raise pull request to fix this and bring this code in accordance to RFC.
Thanks again for highlighting out this issue.
