### ISSUE TITLE
NullPointerException thrown when some other behavior would be preferable

### ISSUE THREAD

**Issue by cyber-front** [flipkart-incubator/zjsonpatch#39]
The following code produces a `NullPointerException` on line 42 of `ApplyProcessor.java`:

    package com.cyberfront.bad_update;
	
    import java.io.IOException;
    import com.fasterxml.jackson.databind.JsonNode;
    import com.fasterxml.jackson.databind.ObjectMapper;
    import com.flipkart.zjsonpatch.JsonPatch;
    
    public class Main {
        private final static String opString = "[{\"op\":\"replace\",\"path\":\"/version\",\"value\":43},{\"op\":\"move\",\"path\":\"/collectionValue/0\",\"from\":\"/collectionValue/1\"},{\"op\":\"add\",\"path\":\"/collectionValue/1\",\"value\":{\"@type\":\"SimpleReference\",\"id\":\"9c144d02-a859-4a9c-be9f-0de6fc77d5ac\",\"notes\":\"voluptatum moderatius dolorum finibus solet vituperata adhuc\",\"description\":\"falli intellegat antiopam mus antiopam\",\"version\":0,\"referenceValue\":{\"@type\":\"SimpleD\",\"id\":\"c75d0410-9729-4688-94fc-d5416a2f716e\",\"notes\":\"condimentum solum simul postea noluisse altera quam eruditi\",\"description\":\"sem egestas senserit curabitur autem\",\"version\":0,\"booleanValue\":true,\"type\":\"SIMPLE_D\"},\"type\":\"SIMPLE_REFERENCE\"}},{\"op\":\"add\",\"path\":\"/collectionValue/4\",\"value\":{\"@type\":\"SimpleB\",\"id\":\"e1011e30-9bd5-470e-a40a-4c3d7b621e16\",\"notes\":\"liber vix elitr interpretaris aliquip dico quidam\",\"description\":\"aenean adversarium vivamus id porta curabitur placerat invidunt\",\"version\":1,\"intValue\":588448685,\"type\":\"SIMPLE_B\"}},{\"op\":\"replace\",\"path\":\"/collectionValue/9/@type\",\"value\":\"SimpleReference\"},{\"op\":\"replace\",\"path\":\"/collectionValue/9/id\",\"value\":\"82141cc1-d655-4905-ba1a-a1a4d9070466\"},{\"op\":\"replace\",\"path\":\"/collectionValue/9/notes\",\"value\":\"interdum nonumes orci vero aptent suavitate\"},{\"op\":\"replace\",\"path\":\"/collectionValue/9/description\",\"value\":\"simul aenean morbi fames tempus veri reformidans\"},{\"op\":\"remove\",\"path\":\"/collectionValue/9/intValue\"},{\"op\":\"replace\",\"path\":\"/collectionValue/9/type\",\"value\":\"SIMPLE_REFERENCE\"},{\"op\":\"add\",\"path\":\"/collectionValue/9/referenceValue\",\"value\":{\"@type\":\"SimpleB\",\"id\":\"39958676-bfa2-4963-8c01-7a0e656fd805\",\"notes\":\"numquam eloquentiam sagittis esse habemus offendit hac lectus sumo\",\"description\":\"feugait interdum expetendis dicam vituperata quem nonumes\",\"version\":0,\"intValue\":1215734120,\"type\":\"SIMPLE_B\"}},{\"op\":\"replace\",\"path\":\"/collectionValue/10/@type\",\"value\":\"SimpleA\"},{\"op\":\"replace\",\"path\":\"/collectionValue/10/id\",\"value\":\"12a3eea0-8636-4735-a4cb-03309eb14dad\"},{\"op\":\"replace\",\"path\":\"/collectionValue/10/notes\",\"value\":\"altera auctor civibus per tempor nonumes quaestio cetero\"},{\"op\":\"replace\",\"path\":\"/collectionValue/10/description\",\"value\":\"gravida sapientem saepe voluptatum aptent pri\"},{\"op\":\"remove\",\"path\":\"/collectionValue/10/intValue\"},{\"op\":\"replace\",\"path\":\"/collectionValue/10/type\",\"value\":\"SIMPLE_A\"},{\"op\":\"move\",\"path\":\"/collectionValue/10/stringValue\",\"from\":\"/collectionValue/11/stringValue\"},{\"op\":\"add\",\"path\":\"/collectionValue/12\",\"value\":{\"@type\":\"SimpleD\",\"id\":\"95a81a99-ce21-40c7-a152-8db57ea34a76\",\"notes\":\"ancillae quisque eget ius praesent omittantur senserit nunc finibus\",\"description\":\"ridens dolorum veritus neque hinc menandri netus\",\"version\":0,\"booleanValue\":false,\"type\":\"SIMPLE_D\"}}]";
        private final static String docString = "{\"@type\":\"SimpleCollection\",\"id\":\"6b9c1dea-566c-4284-aab6-c590658fa02e\",\"notes\":\"fabulas litora labores curabitur vestibulum finibus vehicula risus venenatis\",\"description\":\"pertinacia conubia mi noster electram curabitur dicant dignissim\",\"version\":30,\"collectionValue\":[{\"@type\":\"SimpleA\",\"id\":\"12a3eea0-8636-4735-a4cb-03309eb14dad\",\"notes\":\"altera auctor civibus per tempor nonumes quaestio cetero\",\"description\":\"gravida sapientem saepe voluptatum aptent pri\",\"version\":0,\"stringValue\":\"airline-fan-dream-just\",\"type\":\"SIMPLE_A\"},{\"@type\":\"SimpleB\",\"id\":\"e1011e30-9bd5-470e-a40a-4c3d7b621e16\",\"notes\":\"liber vix elitr interpretaris aliquip dico quidam\",\"description\":\"aenean adversarium vivamus id porta curabitur placerat invidunt\",\"version\":0,\"intValue\":273482951,\"type\":\"SIMPLE_B\"},{\"@type\":\"SimpleB\",\"id\":\"e1011e30-9bd5-470e-a40a-4c3d7b621e16\",\"notes\":\"liber vix elitr interpretaris aliquip dico quidam\",\"description\":\"aenean adversarium vivamus id porta curabitur placerat invidunt\",\"version\":0,\"intValue\":273482951,\"type\":\"SIMPLE_B\"},{\"@type\":\"SimpleB\",\"id\":\"e1011e30-9bd5-470e-a40a-4c3d7b621e16\",\"notes\":\"liber vix elitr interpretaris aliquip dico quidam\",\"description\":\"aenean adversarium vivamus id porta curabitur placerat invidunt\",\"version\":0,\"intValue\":273482951,\"type\":\"SIMPLE_B\"},{\"@type\":\"SimpleB\",\"id\":\"e1011e30-9bd5-470e-a40a-4c3d7b621e16\",\"notes\":\"liber vix elitr interpretaris aliquip dico quidam\",\"description\":\"aenean adversarium vivamus id porta curabitur placerat invidunt\",\"version\":0,\"intValue\":273482951,\"type\":\"SIMPLE_B\"},{\"@type\":\"SimpleC\",\"id\":\"e18f7bec-b247-4058-9a6c-c6b52af26388\",\"notes\":\"option veri pellentesque ultricies adipiscing urbanitas disputationi sed consectetur\",\"description\":\"pertinacia dicam odio ante eu utroque fames altera natoque\",\"version\":0,\"doubleValue\":0.07255739886557588,\"type\":\"SIMPLE_C\"},{\"@type\":\"SimpleB\",\"id\":\"e1011e30-9bd5-470e-a40a-4c3d7b621e16\",\"notes\":\"liber vix elitr interpretaris aliquip dico quidam\",\"description\":\"aenean adversarium vivamus id porta curabitur placerat invidunt\",\"version\":0,\"intValue\":273482951,\"type\":\"SIMPLE_B\"},{\"@type\":\"SimpleC\",\"id\":\"d4cfc023-1ad3-4af2-9d45-969eb1e18497\",\"notes\":\"utroque ocurreret latine mediocritatem aenean porta recteque tristique\",\"description\":\"quam fabulas molestiae pertinax elaboraret mei tempus veritus hinc\",\"version\":0,\"doubleValue\":0.16580470519942858,\"type\":\"SIMPLE_C\"},{\"@type\":\"SimpleC\",\"id\":\"d4cfc023-1ad3-4af2-9d45-969eb1e18497\",\"notes\":\"utroque ocurreret latine mediocritatem aenean porta recteque tristique\",\"description\":\"quam fabulas molestiae pertinax elaboraret mei tempus veritus hinc\",\"version\":0,\"doubleValue\":0.16580470519942858,\"type\":\"SIMPLE_C\"}],\"type\":\"SIMPLE_COLLECTION\"}";
	
        public static void main(String[] args) {
            ObjectMapper mapper = new ObjectMapper();
            JsonNode op = null;
            JsonNode doc = null;
            JsonNode rv = null;
    
            try {
                op = mapper.readTree(opString);
                doc = mapper.readTree(docString);
            } catch (IOException e) {
                e.printStackTrace();
            }
	
            if (null != op && null != doc) {
                rv = JsonPatch.apply(op, doc);
            }

            System.out.println(rv.toString());
        }
    }

The actual exception generated is:

    Exception in thread "main" java.lang.NullPointerException
        at com.flipkart.zjsonpatch.ApplyProcessor.move(ApplyProcessor.java:42)
        at com.flipkart.zjsonpatch.JsonPatch.process(JsonPatch.java:102)
        at com.flipkart.zjsonpatch.JsonPatch.apply(JsonPatch.java:135)
        at com.flipkart.zjsonpatch.JsonPatch.apply(JsonPatch.java:140)
        at com.cyberfront.bad_update.Main.main(Main.java:27)

My pom.xml file is:

    <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
        <modelVersion>4.0.0</modelVersion>
        <groupId>com.cyberfront</groupId>
        <artifactId>bad_update</artifactId>
        <version>0.0.1-SNAPSHOT</version>
  
        <properties>
            <maven.compiler.source>1.8</maven.compiler.source>
            <maven.compiler.target>1.8</maven.compiler.target>
        </properties>

        <dependencies>
            <dependency>
                <groupId>com.flipkart.zjsonpatch</groupId>
                <artifactId>zjsonpatch</artifactId>
            </dependency>
        </dependencies>
        <dependencyManagement>
            <dependencies>
                <dependency>
                    <groupId>com.flipkart.zjsonpatch</groupId>
                    <artifactId>zjsonpatch</artifactId>
                    <version>0.3.1</version>
                </dependency>
            </dependencies>
        </dependencyManagement>
    </project>

Assuming the operation is actually invalid on the given JSON object (which I strongly suspect to be the case, though haven't investigated thoroughly to verify), I would think a more descriptive exception, probably derived from `JsonPatchApplicationException` would be in order here, rather than a `NullPointerException`.

Let me know if you need other examples where this happens; I can generate them more or less on demand or as needed.

Complete zipped Eclipse Neon project is attached.

[bad_update.zip](https://github.com/flipkart-incubator/zjsonpatch/files/1126556/bad_update.zip)

**Comment by cyber-front** [comment]
@holograph I used version 0.3.3, which according to the readme is the latest version, and I still see this behavior.  Is there a version after 0.3.3 I should be using instead?

**Comment by vishwakarma** [comment]
Hi @cyber-front 
This will get fixed by #45 , I will try my best to review & release it.

**Comment by vishwakarma** [comment]
Please try 0.3.4, it should address this issue

**Comment by cyber-front** [comment]
This fixes the issue.  Thanks.
