### ISSUE TITLE
Supporting in-place patch

### ISSUE THREAD

**Issue by hugebdu** [flipkart-incubator/zjsonpatch#41]
@vishwakarma Gopi, hey.

We have in our codebase (event sourcing) a chain of patches we apply one after another and the target JSONs are pretty big.

WDYT about supporting another flavour (ie `JsonPatch.applyInPlace`) without the [`deepCopy()`](https://github.com/flipkart-incubator/zjsonpatch/blob/master/src/main/java/com/flipkart/zjsonpatch/ApplyProcessor.java#L31)

I can prepare a PR.

Thanks in advance!

Daniel

**Comment by vishwakarma** [comment]
I understand your requirement.
Please feel free to raise a PR, it may introduce a new API in existing library for in-place Operations.

Thank you

**Comment by holograph** [comment]
@hugebdu Sounds like a minor variant of `JsonApplyProcessor` (possibly a constructor overload, or  preferably a subclass), is that what you had in mind?

**Comment by hugebdu** [comment]
@holograph ja
