### ISSUE TITLE
Change pom to latest 2.8.10 jackson release

### ISSUE THREAD

**Issue by llper** [flipkart-incubator/zjsonpatch#46]
Hello,
since jackson 2.9 has been released, I would also build a zjsonpatch release targeting jackson 2.8.10 (latest 2.8). This will increase compliance with all software using latest 2.8.10 version.

KR,
D

**Comment by vishwakarma** [comment]
Sure, please feel free to raise a PR

**Comment by llper** [comment]
My eclipse complains about missing permissions when I try to push the branch I've created with the pom change. Do you know what am I doing wrong ?

**Comment by vishwakarma** [comment]
I think first you need to fork this project, then commit the changes into that forked branch.
Then you come to original repo and raise a pull request by comparing this repo and your forked repo.
Let me know if you need any assistance on this.

**Comment by vishwakarma** [comment]
Merged the #47 , will release new version as 0.3.5

Thanks for PR
