### ISSUE TITLE
Option to turn off copy and move

### ISSUE THREAD

**Issue by PeterBackman** [flipkart-incubator/zjsonpatch#48]
The operations move and copy implies a relation between "from" and "path". This is based on matching values but that might not be a true relation.

Consider these examples:

First: `{"age": 10}`
Second: `{"height": 10}`
Patch result: `[{"op":"move","from":"/age","path":"/height"}]`

or 

Second: `{"age": 10, "height": 10}`
Patch result: `[{"op":"copy","from":"/age","path":"/height"}]`

"age" does not have any relation with "height", they just happen to have the same value.

Not all systems apply JSON patches to existing JSON structures. We have use cases for subscribing on changes based on the "path". Also use cases on acting differently (or not at all) based on what "path" is changed. This would be a lot simpler if only add/remove/replace are used. 

My proposal is to add a flag omitting copy/move. Would you consider this as a valid addition to this library?

**Comment by vishwakarma** [comment]
Sure, I understand your use-case and concerns.

 --- Bit of background ( reason for having Move & Copy Operations )
These operations (Move & Copy) were included to reduce the size of patch ( sequence of diffs ) generated. [RFC](https://tools.ietf.org/html/rfc6902#section-4.4).

Shall i take on the development of this ? or you wanna try it out ?. 
I see we can easily incorporate this change by using our following api -
`JsonNode asJson(final JsonNode source, final JsonNode target, EnumSet<DiffFlags> flags)`

**Comment by PeterBackman** [comment]
Thanks for a fast reply!

It would be excellent if you could implement this according to your suggestion.

In our case size do not matter but I understand that it can be important in other cases.

**Comment by vishwakarma** [comment]
Sure
I will take on this ASAP.

**Comment by vishwakarma** [comment]
Hi @PeterBackman 
I have raised a PR #49 , Can you please review & test once ( just to make sure, it addresses your use-cases & concerns )

**Comment by PeterBackman** [comment]
Code looks good and it worked fine when I used it in a small test application. I am very happy with this solution.

A possible improvement is to add a section in the README describing the possibility to change the behaviour of the patch generation via flags. Could be good for new users.

/BR Peter

**Comment by vishwakarma** [comment]
Sure

**Comment by vishwakarma** [comment]
Please use 0.3.5 version
