### ISSUE TITLE
Non intuitive behaviour of flags

### ISSUE THREAD

**Issue by PeterBackman** [flipkart-incubator/zjsonpatch#51]
If I use `asJson(final JsonNode source, final JsonNode target)` I get the default behaviour which is to omit the value in remove.
If I use `asJson(final JsonNode source, final JsonNode target, EnumSet<DiffFlags> flags)` with no flags I do not get the default behaviour. This is non intuitive. This also means that if I want to use another flag on top of the default behaviour I need to add the `OMIT_VALUE_ON_REMOVE` flag as well.

I propose:
*`OMIT_VALUE_ON_REMOVE` is replaced by `ADD_VALUE_ON_REMOVE`.
*`DiffFlags.defaults()` is an empty set.
This way the library will be more intuitive to use.

**Comment by holograph** [comment]
I would prefer a fluent API to just inverting the semantics, something
along the lines of `DiffFlags.defaults().except(OMIT_VALUE_ON_REMOVE)`. But
that's just me :-)  The main qualm though is that what you're proposing is
a breaking API change.
