### ISSUE TITLE
Testing for a pointer that references a nonexistent value

### ISSUE THREAD

**Issue by acchaulk** [flipkart-incubator/zjsonpatch#53]
I would like to have a "test" operation that asserts a value is missing from an object. Would this be the correct way to do so?

```json
[
  {
    "op": "test",
    "path": "nonexistentField",
    "value": null
  }
]
```
Currently, this library will throw an exception "noSuchPath in source". Does it make sense to add this feature to the library?

**Comment by vishwakarma** [comment]
Sure, Please feel free to raise a PR.

**Comment by holograph** [comment]
That is strictly a nonstandard extension and should be handled with care.

From the RFC section 4.6: “The "test" operation tests that a value at the
target location is
equal to a specified value.”

In other words the discussed feature literally subverts the semantics of
the standard.

**Comment by acchaulk** [comment]
Per the "Error Handling" section of the [RFC on JSON Pointers](https://tools.ietf.org/html/rfc6901#section-7):

> Error conditions include, but are not limited to:
>
> * Invalid pointer syntax
> * A pointer that references a nonexistent value
>
>This specification does not define how errors are handled. An application of JSON Pointer SHOULD specify the impact and handling of each type of error.
>
>For example, some applications might stop pointer processing upon an error, while others may attempt to recover from missing values by inserting default ones.

I am fine with not implementing this and am looking for a mechanism to test for a non-existent pointer.
