### ISSUE TITLE
bug in json array removed.

### ISSUE THREAD

**Issue by PriyangaSubramanian** [flipkart-incubator/zjsonpatch#56]
If i compare the below two jsons,
Json 1:
`{"a":{"b":[{"value":0},{"value":1},{"value":2}]}}`

Json 2:
`{"a":{"b":[]}}`

The result I am getting is,
[{"op":"remove","path":"/a/b/0"},{"op":"remove","path":"/a/b/0"},{"op":"remove","path":"/a/b/0"}]

The actual result should be

> [{"op":"remove","path":"/a/b/0"},{"op":"remove","path":"/a/b/1"},{"op":"remove","path":"/a/b/2"}]

**Comment by holograph** [comment]
This is not a bug, but completely on [spec](https://tools.ietf.org/html/rfc6902#section-4.2):

```
4.2.  remove

   The "remove" operation removes the value at the target location.

   The target location MUST exist for the operation to be successful.

   For example:

   { "op": "remove", "path": "/a/b/c" }

   If removing an element from an array, any elements above the
   specified index are shifted one position to the left.
```

The shift to the left moves subsequent elements to the 0th index. In conjunction with the RFC [section 3](https://tools.ietf.org/html/rfc6902#section-3):

```
   Evaluation of a JSON Patch document begins against a target JSON
   document.  Operations are applied sequentially in the order they
   appear in the array.  Each operation in the sequence is applied to
   the target document; the resulting document becomes the target of the
   next operation.  Evaluation continues until all operations are
   successfully applied or until an error condition is encountered.
```

This means the target is mutable, so this is actually the correct response.

**Comment by holograph** [comment]
Actually, your example should fail to process, whereas the reverse (remove index 2, then 1, then 0) would work fine :-)

**Comment by Alex-Cook4** [comment]
I have a similar issue with: 

```
JSON 1: 
{
  "id" : 53,
  "authorities" : [ "AUTH_U" ]
}

JSON 2: 
{
  "id" : 53,
  "authorities" : [ "AUTH_A", "AUTH_U", "AUTH_AD", "AUTH_IN", "AUTH_OP" ]
}

Result: 
[{"op":"remove","path":"/authorities/0"},{"op":"remove","path":"/authorities/1"},{"op":"remove","path":"/authorities/1"},{"op":"remove","path":"/authorities/1"}]
```
I was expecting to get: 
```
[{"op":"remove","path":"/authorities/0"},{"op":"remove","path":"/authorities/2"},{"op":"remove","path":"/authorities/3"},{"op":"remove","path":"/authorities/4"}]
```
Which would help me identify the elements that were actually removed. 

If I run in reverse, I get what I expect: 

```
[{"op":"add","path":"/authorities/0", "value":"val0"},{"op":"add","path":"/authorities/2", "value":"val2"},{"op":"add","path":"/authorities/3", "value":"val3"},{"op":"add","path":"/authorities/4", "value":"val4"}]
```

**Comment by vishwakarma** [comment]
Thanks @holograph for the clarification. 
@PriyangaSubramanian @Alex-Cook4 , please let me know if any further clarification is needed on this.
IMO, the specification refers to Patch ( not diff ) which is series of operation when applied to source json to generate target json.
