### ISSUE TITLE
Diff Replace - does not contain original value

### ISSUE THREAD

**Issue by MihaiMihalache** [flipkart-incubator/zjsonpatch#57]
When doing a diff between two jsons, for the REPLACE operation the fieldChanges should contain also the original value. I can work on this feature as I think it brings value to this library.

**Comment by vishwakarma** [comment]
Hi @MihaiMihalache , please refer to my comment on your PR.
Thanks

**Comment by MihaiMihalache** [comment]
Hi vishwakarma, 
I updated the PR.
Thx!

**Comment by vishwakarma** [comment]
PR merged
