### ISSUE TITLE
Interest to remove/migrate apache and guava dependencies

### ISSUE THREAD

**Issue by LouizFC** [flipkart-incubator/zjsonpatch#59]
while reading the source code, I realized that most of the methods used from apache and guava libraries could be ported to the kotlin std lib or written by hand. I think that the library would benefit much from the shrink in dependencies, since guava is almost 2.5MB

So I ask if there is interest in migrating? I can make a commit for this after the holidays. My only worries are about java 6 compability (in kotlin std lib case) and perfomance.

The main difficult of the port would be the apache LCS algorithm that JsonDiff uses.

**Comment by vishwakarma** [comment]
I agree, removal of apache and guava dependency will make this library more slim and useable.
It would be more preferred if this library remains compatible with all java versions.
All corresponding replacements of guava and apache usage can be replaced easily ( More than 1000 test cases to verify that ).
I can pick this task since i am already aware of the codebase, but let me know the otherwise, i would be available for any help needed?

Thanks

**Comment by LouizFC** [comment]
@vishwakarma Thank you. Because english is not my primary language I had some difficult understanding you last question, I am sorry.

for what I understanded: I will commit the changes in the source and you will change the tests?

another question: would you prefer to move all the new methods to a "InternalUtils.java" or declare each method inside the class that uses it?

**Comment by vishwakarma** [comment]
Hi @LouizFC 
No problem :)
I have raised a PR #60 , which contains removal of apache commons dependency (Wrote own LCS). Please review it and kindly make further changes in the same branch for  removal of guava dependency.
I have a large test suite ( 16M json docs & updates ) apart from one checked-in with this library, I will use it to validate all our changes.

**Comment by LouizFC** [comment]
Thank you @vishwakarma 
I am doing the changes now.
I have two questions so far:

- Can I rename the "getArrayNodeRepresentation" to "getPathRepresentation"? it's a private api method, so I think it will not bother anyone.
- In the JsonPatch#getPath method, there is the following code:

```java
List<String> paths = Splitter.on('/').splitToList(path.toString().replaceAll("\"", ""));
return Lists.newArrayList(Iterables.transform(paths, DECODE_PATH_FUNCTION));
```
There in the `replaceAll("\"", "")`, it is actually removing all the quotes from the JsonNode String representation. Is this intended? if I have a jsons like:
```json
{"\"a\"": 1}
```
and 
```json
{"\"b\"": 1}
```
and do this:
```java
JsonDiff.asJson(jsonA, jsonB)
```
I end up with the following patch:
```json
[{"op":"move","from":"/\"a\"","path":"/\"b\""}]
```
and if I apply the patch like this:
```java
JsonPatch.apply(patch, jsonA)
```
I end up with the following json:
```json
{"\"a\"":1,"\\b\\": null}
```

**Comment by vishwakarma** [comment]
Sure @LouizFC , Please go ahead
and regarding "**replaceAll("\"", "")**", I will check this and get back to you

**Comment by LouizFC** [comment]
JsonNode has a method called "asText". Seeing the implementation of JsonNode, it creates a TextNode for holding string values. It stores the value without quotes, and you can retrieve this value using "asText" maybe that can help.

**Comment by vishwakarma** [comment]
I will try out "asText"
