### ISSUE TITLE
Deploy artifact on maven central

### ISSUE THREAD

**Issue by NargiT** [flipkart-incubator/zjsonpatch#6]
Hello,

Could you please deploy this artifact on maven central repository http://search.maven.org/ ? 

Thx !

**Comment by vishwakarma** [comment]
Hi
I have raised a JIRA ticket to upload zjsonpatch to maven central, once they grant the permission I will push it same.
Meanwhile, you can access this project via clojars too by mentioning 
Add following to `<repositories/>` section of pom.xml -
```xml
<repository>
  <id>clojars</id>
  <name>Clojars repository</name>
  <url>https://clojars.org/repo</url>
</repository>
```

**Comment by vishwakarma** [comment]
JIRA link : https://issues.sonatype.org/browse/OSSRH-17441

**Comment by NargiT** [comment]
Its perfectly working no worries, its just more practical to have on maven central.

Thx !

**Comment by sharathsrinivasa** [comment]
Hello,

Is this already deployed to mvn central repository? I still don't find it there.

Thanks!

**Comment by vishwakarma** [comment]
Hey sharath, i m not getting time to deploy on maven, will do once i get chance.
Please use clojars meanwhile to download this project as dependency as follow -

Add following to `<repositories/>` section of pom.xml -
```xml
<repository>
  <id>clojars</id>
  <name>Clojars repository</name>
  <url>https://clojars.org/repo</url>
</repository>
```
Add following to `<dependencies/>` section of your pom.xml -

```xml
<groupId>com.flipkart.zjsonpatch</groupId>
<artifactId>zjsonpatch</artifactId>
<version>0.2.1</version>
```

**Comment by sharathsrinivasa** [comment]
I understand how to use zjsonpatch. But, due to some policy, I could not use clojars to pull in the artifact. Could you please upload this artifact  to mvn central ASAP? That would be really great.

Thanks!

**Comment by vishwakarma** [comment]
Hey
I have deployed on maven, can you please check now
https://repo1.maven.org/maven2/com/flipkart/zjsonpatch/zjsonpatch/0.2.1/

**Comment by sectrait** [comment]
http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.flipkart.zjsonpatch%22

**Comment by sectrait** [comment]
@vishwakarma 
Thanks.

**Comment by vishwakarma** [comment]
Since it is available on maven, closing this ticket
