### ISSUE TITLE
Replace of non existing path results in addition of that path

### ISSUE THREAD

**Issue by Anatolii** [flipkart-incubator/zjsonpatch#65]
Thanks for a great library!

I found this issue which is possible to reproduce in version 0.4.2

Given I have source json:
{ }
When I apply patch:
[
  {
    "op" : "replace",
    "path" : "some-not-existing-path",
    "value" : "some-value"
  }
]
Then I get result:
{
  "some-not-existing-path" : "some-value"
}

I would expect that implementation will throw an exception or will skip replacement of something which does not exist.

According to the RFC-6902 specification (https://tools.ietf.org/html/rfc6902#section-4.3):
The Replace operation functionally is identical to a "remove" operation for a value, followed immediately by an "add" operation at the same location with the replacement value.
For the Remove operation target location MUST exist for the operation to be successful.

**Comment by vishwakarma** [comment]
Agreed as per RFC "The target location MUST exist for the operation to be successful".
I will look into the library for this bug and will fix it as soon as possible if required.

**Comment by holograph** [comment]
Might want to add a backwards compatibility flag as well, this may break
existing clients
