### ISSUE TITLE
add change log tracking file

### ISSUE THREAD

**Issue by danieldonev** [flipkart-incubator/zjsonpatch#67]
It would be really useful to have CHANGELOG.md where we can see the version changes.

**Comment by dandoug** [comment]
There's always the info at https://github.com/flipkart-incubator/zjsonpatch/releases

**Comment by vishwakarma** [comment]
Thanks @dandoug 
Hi @danieldonev, I will try to be more descriptive regarding changes pushed with each release at https://github.com/flipkart-incubator/zjsonpatch/releases. Since I haven't maintained separate CHANGELOG.md, please use releases section for changes pushed.
