### ISSUE TITLE
Bug - compared to json

### ISSUE THREAD

**Issue by milka0013** [flipkart-incubator/zjsonpatch#68]
From the version (0.3.*) when comparing two json differing only in one verse, I get "copy" error  instead  of "add" 
e.g
`{"data1":"data1","value":null,"dataList":[],"data3":{"amount":17.2,"currency":"EU"},"type":"type"}`

`{"__data":null,"data1":"data1","value":null,"dataList":[],"data3":"amount":17.2,"currency":"EU"},"type":"type"}`

result : 
`[{"op":"copy","from":"/type","path":"/__data"}]`

**Comment by vishwakarma** [comment]
@milka0013 
It's because of COPY Operation, As per specs ADD operation is used when a new value is introduced in json, if we can re-use an existing value then COPY is preferred.

**Comment by milka0013** [comment]
but those are different only  __data value. First Json hasn't this value.

**Comment by vishwakarma** [comment]
Hi @milka0013 
There is a difference in the output i have got.
Json1 => {"data1":"data1","value":null,"dataList":[],"data3":{"amount":17.2,"currency":"EU"},"type":"type"}

Json2 : {"__data":null,"data1":"data1","value":null,"dataList":[],"data3":{"amount":17.2,"currency":"EU"},"type":"type"}

patch : [{"op":"copy","from":"/value","path":"/__data"}]

Here in the patch, it says copy the data present at "/value" to path "/__data" which is "null"

**Comment by vishwakarma** [comment]
Hi @milka0013, Please let me know if above answered your question?
