### ISSUE TITLE
ADD

### ISSUE THREAD

**Issue by sbaunthiyal** [flipkart-incubator/zjsonpatch#79]
Hello , I was expected "op":"add" for the following comparison. 

**target** : {"title":null,"firstName":"William","middleName":null,"lastName":null,"gender":"Male"}
**source** : {"title":null,"firstName":null,"middleName":null,"lastName":null,"gender":null}
**Result** : [{"op":"replace","path":"/firstName","value":"William"}, "op":"replace","path":"/gender","value":"Male"}]

Code : JsonNode resultJson = JsonDiff.asJson(
            source,target);
 
Version : 0.4.5

Is it expected response or am I missing anything?

Thanks
Shashank

**Comment by vishwakarma** [comment]
Operation Add indicates the creation of new fields in JSON.
Operation Replace indicates updating existing fields value in JSON.

In above example:
Field William already exists, so we just need to update its existing value.
In case, field William didn't exist then we would have created a field with value

**Comment by sbaunthiyal** [comment]
Hi Vishwakarma , Thanks for the quick response 

Here is my use case. I’ve two instances of Person class. The new one has values populated whereas Old one has null or spaces. Now I convert both to Json and feed to your method. The operation I was expecting as ADD since values added to elements(firstName,lastName,gender) whereas in old they were Null/Spaces.

ObjectMapper mapper = new ObjectMapper();
        
Person personNew = new Person("William","Fork","Male");
JsonNode personNewJson = mapper.convertValue(personNew,JsonNode.class);
System.out.println("source :" + personNewJson);
       
Person personOld = new Person(null,null,null);
JsonNode personOldJson = mapper.convertValue(personOld,JsonNode.class);  
System.out.println("target :" + personOldJson);
       
JsonNode resultJson = JsonDiff.asJson(personOldJson,personNewJson);
System.out.println("Result : " + resultJson);

Console :

source :{"firstName":"William","lastName":"Fork","gender":"Male"}
target :{"firstName":null,"lastName":null,"gender":null}
Result : [{"op":"replace","path":"/firstName","value":"William"},{"op":"replace","path":"/lastName","value":"Fork"},{"op":"replace","path":"/gender","value":"Male"}]

Please let me know if my expectations are wrong.

**Comment by sbaunthiyal** [comment]
Okay , I created one more class Person1 with additional variable "Age" , When Person and Person 1 are compared. It responded with "ADD".

So now my understanding is JsonDiff.asJson will revert with "ADD" when new element is added not when **value** to element is added.

Right ?

**Comment by vishwakarma** [comment]
Yes, you are right
