### ISSUE TITLE
complex json array，the result of comparison is inaccurate.

### ISSUE THREAD

**Issue by shaozhengmao** [flipkart-incubator/zjsonpatch#88]
eg.  
source:[6772982,20190118,[19]]
target:[6772982]

> EnumSet<DiffFlags> flags = DiffFlags.dontNormalizeOpIntoMoveAndCopy().clone();
        JsonNode diffResultNode = JsonDiff.asJson(actualNode, expectNode, flags);
        System.out.println(diffResultNode);

result:
[{"op":"remove","path":"/1","value":20190118},{"op":"remove","path":"/1","value":[19]}]

i think, the result should be：
[{"op":"remove","path":"/1","value":20190118},{"op":"remove","path":"/2","value":[19]}]

**Comment by holograph** [comment]
Sorry but you got it wrong: the patch is applied sequentially and _mutates_ the resulting node, so referencing `/2` would actually be invalid and error out (see [RFC 6902](https://tools.ietf.org/html/rfc6902#section-3) section 3: "Operations are applied sequentially in the order they appear in the array.  Each operation in the sequence is applied to the target document; the resulting document becomes the target of the next operation.")

**Comment by shaozhengmao** [comment]
> Sorry but you got it wrong: the patch is applied sequentially and _mutates_ the resulting node, so referencing `/2` would actually be invalid and error out (see [RFC 6902](https://tools.ietf.org/html/rfc6902#section-3) section 3: "Operations are applied sequentially in the order they appear in the array. Each operation in the sequence is applied to the target document; the resulting document becomes the target of the next operation.")

i get it, thanks ;)
