### ISSUE TITLE
RFC6901 compliance may present backward incompatible changes

### ISSUE THREAD

**Issue by LouizFC** [flipkart-incubator/zjsonpatch#89]
I was working on as PR for #82. I found the this lib lacks a test for RFC6901 (JsonPointer specification), I should have noted this on #60, for which I am sorry.

I have read thru the [RFC6091 spec](https://tools.ietf.org/html/rfc6901). The doc presents a very simple Json for tests at [section 5](https://tools.ietf.org/html/rfc6901#section-5):

```json
   {
      "foo": ["bar", "baz"],
      "": 0,
      "a/b": 1,
      "c%d": 2,
      "e^f": 3,
      "g|h": 4,
      "i\\j": 5,
      "k\"l": 6,
      " ": 7,
      "m~n": 8
   }
```
I have added a test to our lib:
```java
JsonNode testData = TestUtils.loadResourceAsJsonNode("rfc6901.json");
JsonNode emptyJson = TestUtils.DEFAULT_MAPPER.createObjectNode();

JsonNode patch = JsonDiff.asJson(emptyJson, testData);
JsonNode result = JsonPatch.apply(patch, emptyJson);
assertEquals(testData, result);
```
Which produces the following output (formatted for clarity):
```
Expected:                Actual:
{                        {
   "foo":[                   "foo":[
      "bar",                    "bar",
      "baz"                     "baz"
   ],                        ],
   "":0,                     "":0,
   "a/b":1,                  "a/b":1,
   "c%d":2,                  "c%d":2,
   "e^f":3,                  "e^f":3,
   "g|h":4,                  "g|h":4,
   "i\\j":5,                 "i\\\\j":5,
   "k\"l":6,                 "k\\l":6,
   " ":7,                    " ":7,
   "m~n":8                   "m~n":8
}                         }
```
The test `ì` fails, and is related to #82.  
The test `k` also fails, and is related to https://github.com/flipkart-incubator/zjsonpatch/issues/59#issuecomment-353739193

Fixing this issue would break backwards compatibility, so I would like some feedback before working on a fix.

**Comment by LouizFC** [comment]
@holograph @vishwakarma  do you think we can close this? I was worried about backward compatibility

**Comment by holograph** [comment]
The worry is legitimate, but I honestly don’t know if anyone is likely to
run into this (these are fairly esoteric cases). My 2 cents: close it and
reopen as a backwards compatibility issue if anyone complains (otherwise it
just pollutes the api unnecessarily).

**Comment by LouizFC** [comment]
@holograph agreed. Thank you for your input
