### ISSUE TITLE
Supporting wildcard in path

### ISSUE THREAD

**Issue by AshishHNP** [flipkart-incubator/zjsonpatch#93]
Hello,
I was wondering if its possible to add support for wildcard in path.

```
{
"biscuits": [
{ "name": "Digestive" },
{ "name": "Choco Leibniz" }
]
}
```

In the example of:
`{ "op": "replace", "path": "/biscuits/*/name", "value": { "name": "ChangeEverything" } }`

would lead to:

```
{
"biscuits": [
{ "name": "ChangeEverything" },
{ "name": "ChangeEverything" }
]
}

```
In case we aren't sure the amount of entries in an array, supporting this could help generalize it and allow updates everywhere. JsonPath library I believe supports it, but not sure if its practical to use it here. I will take a stab at it myself, but first wanted to get your thoughts if this has been something you have heard of before or tried.
Thanks

**Comment by holograph** [comment]
JSON Patch (RFC 6902) is built on top of JSON Pointer ([RFC 6901](https://tools.ietf.org/html/rfc6901)), which doesn't support wildcards. This would be a nonstandard extension that wouldn't be compatible with _any_ other implementation, so for my money it wouldn't be advisable to support this. @vishwakarma ?

**Comment by vishwakarma** [comment]
I agree with @holograph, We should not diverge from RFC.
