### ISSUE TITLE
Crash with "remove" operation when path contains a large integer value.

### ISSUE THREAD

**Issue by oactivation** [flipkart-incubator/zjsonpatch#98]
Hi Json Patch team,

We are using zjson patch to help us manage user preferences, we use unix timestamps as a unique ID in the data we are storing.  When we use a remove operation on paths that include these keys we get a crash in JsonDiff.java.  Here is a sample patch operation that produces it: 
{"op":"remove","path":"/profiles/AdvancedCharting/profiles/1509638193736/tradingView/data/charts/0/panes/0/sources/96/metaInfo/matchIndex"}

The problem comes from the timestamp key "1509638193736". The crash occurs at line 104 in JsonDiff.java, it seems to be trying to detect if any of the items in the path are integers using the "isInteger" function and then cast them to integers if they are.  However, the timestamps appear as integers but are much larger than the largest possible integer so when the cast to int is attempted it fails and crashes. 

Please let me know if there is any more information I can provide.

**Comment by LouizFC** [comment]
Hello @oactivation , thanks for reaching us out

could you please inform what version you are having this issue? this sounds very familiar, I think we already fixed it some time ago.

**Comment by oactivation** [comment]
Hi,
Thanks very much for the speedy response, the linked issue looks to be the same as what we are experiencing and we are on a version that pre-dates that fix.  I am working now to upgrade our version and verify the fix but I think that you should consider this issue a duplicate.  I will close the issue when I confirm, thanks very much for your help.
